defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/root/dev.cams7-job.ml.cert"
        keyFile = "/root/dev.cams7-job.ml.key"
      [[entryPoints.https.tls.certificates]]
        certFile = "/root/traefik.cams7-job.ml.cert"
        keyFile = "/root/traefik.cams7-job.ml.key"
      [[entryPoints.https.tls.certificates]]
        certFile = "/root/rabbitmq.cams7-job.ml.cert"
        keyFile = "/root/rabbitmq.cams7-job.ml.key"
      [[entryPoints.https.tls.certificates]]
        certFile = "/root/registry.cams7-job.ml.cert"
        keyFile = "/root/registry.cams7-job.ml.key"
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$2y$10$8LNjDcC//Cz8D02GqfVMY.T4Y1snWnzi5MKK4nuI02jfYgRXMYp/i"] #admin:admin

[api]
  entrypoint="dashboard"

[docker]
  network = "sockshop"
